"""Add chapter_id, module_id, and page_url to book_content

Revision ID: 65face620c30
Revises: 9b67d188e1c6
Create Date: 2025-11-29 21:06:37.543300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65face620c30'
down_revision: Union[str, Sequence[str], None] = '9b67d188e1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_content', sa.Column('chapter_id', sa.String(), nullable=True))
    op.add_column('book_content', sa.Column('module_id', sa.String(), nullable=True))
    op.add_column('book_content', sa.Column('page_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_book_content_chapter_id'), 'book_content', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_book_content_module_id'), 'book_content', ['module_id'], unique=False)
    op.create_index(op.f('ix_book_content_page_url'), 'book_content', ['page_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_content_page_url'), table_name='book_content')
    op.drop_index(op.f('ix_book_content_module_id'), table_name='book_content')
    op.drop_index(op.f('ix_book_content_chapter_id'), table_name='book_content')
    op.drop_column('book_content', 'page_url')
    op.drop_column('book_content', 'module_id')
    op.drop_column('book_content', 'chapter_id')
    # ### end Alembic commands ###
