"""add_translated_content_table

Revision ID: abc4dc8e358c
Revises: e7f97eb76c81
Create Date: 2025-11-30 14:14:09.970148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc4dc8e358c'
down_revision: Union[str, Sequence[str], None] = 'e7f97eb76c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translated_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.String(length=100), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('profile_hash', sa.String(length=64), nullable=False),
    sa.Column('original_content_hash', sa.String(length=64), nullable=False),
    sa.Column('translated_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_translated_chapter_profile_lang', 'translated_content', ['chapter_id', 'profile_hash', 'target_language'], unique=False)
    op.create_index('idx_translated_content_hash', 'translated_content', ['original_content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_translated_content_hash', table_name='translated_content')
    op.drop_index('idx_translated_chapter_profile_lang', table_name='translated_content')
    op.drop_table('translated_content')
    # ### end Alembic commands ###
